# FROM openjdk:11-jre-
FROM openjdk:25-jdk-slim

# Working directory in the container
WORKDIR /app

# Copy JAR file and the wait-for-it.sh script to the container
COPY asert-api/build/libs/api-0.0.1-SNAPSHOT.jar app.jar
COPY config/wait-for-it.sh /app/wait-for-it.sh

# Copy GePG PFX keys to the container
COPY config/keys/ /app/asert-gepg-keys/

# Copy the config files to a temporary location
COPY config/.env /app/.env
COPY config/application.yaml /app/application.yaml
COPY config/application-dev.yaml /app/application-dev.yaml
COPY config/application-prod.yaml /app/application-prod.yaml
COPY config/github.properties /app/github.properties

# Make sure wait-for-it.sh has execution permissions
RUN chmod +x /app/wait-for-it.sh

# Expose the application port
EXPOSE 8080

# Run the JAR file using the wait-for-it.sh script
ENTRYPOINT ["./wait-for-it.sh", "asert-rabbitmq:5672", "--", "java", "-jar", "app.jar"]